name: Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install PHP 8.5
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.5
      - name: Install packages
        run: composer install --no-progress --no-dev
      - name: Dump autoload
        run: composer dump-autoload -o
      - name: Deploy to Landviz.nl
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: sftp
          remote-host: ${{ secrets.SFTP_IP }}
          remote-user: ${{ secrets.SFTP_USERNAME }}
          remote-path: "./webroots/www"
          remote-password: ${{ secrets.SFTP_PASSWORD }}
          sync: full
