name: Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install PHP 8.5
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.5
      - name: Install packages
        run: composer install --no-progress --no-dev
      - name: Dump autoload
        run: composer dump-autoload -o
      - name: Deploy to Landviz.nl
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          server: ${{ secrets.SFTP_IP }}
          port: ${{ secrets.SFTP_PORT }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          sftp_only: true
          local_path: './*'
          remote_path: './webroots/www'
